import React, { useMemo, useState } from "react";
import { parentMatches } from "./planningBoardUtils";

const groupOrder = ["BEDLINER|OEM", "BEDLINER|FCSD", "TPO|OEM", "TPO|FCSD", "TPO|"];
const groupLabel = (key) => key === "TPO|" ? "TPO SHOP-FLOOR PRODUCTS" : key.replace("|", " ");
export default function PlanningCellEditor({ cell, entry, parents, onSave, onClear, onClose, productionLine = "blowMoulding", bomStatus, missingAliases = [] }) {
  const thermo = productionLine === "thermoforming";
  const [type, setType] = useState(entry?.status === "OFF" ? "OFF" : entry?.status === "Changeover" ? "Changeover" : "Production");
  const [partNumber, setPartNumber] = useState(entry?.partNumber || ""), [query, setQuery] = useState(""), [buildQty, setBuildQty] = useState(entry?.buildQty || ""), [status, setStatus] = useState(["Planned", "In progress", "Completed", "Blocked"].includes(entry?.status) ? entry.status : "Planned"), [error, setError] = useState(missingAliases.length ? `${missingAliases.map((item) => `${item.shortName} (${item.stockCode})`).join(", ")} not available in current SYSPRO BOM.` : "");
  const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return parents.filter((p) => !q || parentMatches(p, q) || p.family?.toLowerCase().includes(q) || p.market?.toLowerCase().includes(q)); }, [parents, query]);
  const selected = parents.find((p) => p.stockCode === partNumber);
  const invalidHistorical = Boolean(thermo && entry?.partNumber && !parents.some((p) => p.stockCode === entry.partNumber));
  const groups = useMemo(() => groupOrder.map((key) => ({ key, label: groupLabel(key), parents: filtered.filter((p) => `${p.family}|${p.market || ""}` === key) })).filter((g) => g.parents.length), [filtered]);
  function select(parent) { setPartNumber(parent.stockCode); setQuery(""); setError(""); }
  function submit(e) { e.preventDefault(); const qty = Number(buildQty), valid = parents.some((p) => p.stockCode === partNumber); if (type === "Production" && (!valid || qty <= 0)) return setError("Select a currently valid SYSPRO BOM parent and enter a quantity greater than zero."); if (type === "Changeover" && qty > 0 && !valid) return setError("Select a currently valid changeover destination."); onSave({ ...cell, id: entry?.id || `plan_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`, partNumber: type === "OFF" ? "" : partNumber, buildQty: type === "OFF" ? 0 : Math.max(0, qty), status: type === "Production" ? status : type }); }
  const option = (p) => <button type="button" role="option" key={p.id} onClick={() => select(p)}><strong>{thermo ? p.displayCode : p.stockCode}{p.isPair && <em>PAIRED MOULD</em>}</strong><span>{thermo ? p.stockCode : p.description || "Description unavailable"}</span><span>{thermo ? `${p.description || "Description unavailable"} · ${p.family === "BEDLINER" ? "Bedliner" : "TPO"}${p.market ? ` · ${p.market}` : ""}` : p.linkedParents?.join(" / ") || p.alias}</span></button>;
  return <div className="bm-editor-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="bm-editor" onSubmit={submit}><div className="bm-editor-title">{cell.machine.replace("BM0", "BM")} · {cell.day} · {cell.shift}</div><label>Activity<select value={type} onChange={(e) => setType(e.target.value)}><option>Production</option><option>OFF</option><option>Changeover</option></select></label>{type !== "OFF" && <div className="bm-parent-picker">{thermo && bomStatus?.loading && <div className="bm-editor-error">Loading SYSPRO BOM parents…</div>}{thermo && !bomStatus?.connected && !bomStatus?.loading && <div className="bm-editor-error">SYSPRO BOM unavailable. Parent selection requires live SYSPRO data.</div>}{invalidHistorical && <div className="bm-editor-error">Previously selected parent is no longer valid for {cell.machine}. Select a new valid parent.</div>}<label>{type === "Changeover" ? "Destination" : "Parent stock code"}<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search code, description, family or market…" /></label>{partNumber && <div className="bm-parent-selected"><strong>{selected?.stockCode || partNumber}</strong><span>{selected?.description || "Description unavailable"}</span>{thermo && selected && <small>Family: {selected.family === "BEDLINER" ? "Bedliner" : "TPO"} · Market: {selected.market} · Source: SYSPRO</small>}<button type="button" onClick={() => setPartNumber("")}>Change</button></div>}{!partNumber && <div className="bm-parent-results" role="listbox">{thermo ? groups.map((g) => <div className="bm-parent-group" key={g.key}><div className="bm-parent-group-title">{g.label}</div>{g.parents.map(option)}</div>) : filtered.slice(0, 50).map(option)}{!filtered.length && <div className="bm-parent-empty">No valid SYSPRO BOM parent matches.</div>}</div>}</div>}{type !== "OFF" && <label>Build quantity<input type="number" min="0" step="any" value={buildQty} onChange={(e) => setBuildQty(e.target.value)} /></label>}{type === "Production" && <label>Workflow status<select value={status} onChange={(e) => setStatus(e.target.value)}><option>Planned</option><option>In progress</option><option>Completed</option><option>Blocked</option></select></label>}{error && <div className="bm-editor-error">{error}</div>}<div className="bm-editor-actions">{entry && <button type="button" className="danger" onClick={onClear}>Clear cell</button>}<span /><button type="button" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save</button></div></form></div>;
}
