import React, { useMemo, useState } from "react";
import { parentMatches } from "./planningBoardUtils";

const newRun = () => ({ id: `plan_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`, partNumber: "", buildQty: "", status: "Planned", activity: "Production" });
export default function ShiftPlanningEditor({ cell, entries, parents, onSave, onClose, productionLine, bomStatus, missingAliases = [] }) {
  const [runs, setRuns] = useState(() => entries.length ? entries.map((entry) => ({ ...entry, activity: entry.status === "Changeover" ? "Changeover" : "Production" })) : [newRun()]);
  const [off, setOff] = useState(entries.length === 1 && entries[0].status === "OFF"), [error, setError] = useState("");
  function update(id, patch) { setRuns((current) => current.map((run) => run.id === id ? { ...run, ...patch } : run)); }
  function setShiftOff(checked) { if (checked && runs.some((run) => run.partNumber || Number(run.buildQty) > 0) && !window.confirm(`This shift contains ${runs.length} planned production run${runs.length === 1 ? "" : "s"}. Changing it to OFF will remove them. Continue?`)) return; setOff(checked); if (checked) setRuns([]); else setRuns([newRun()]); }
  function submit(event) { event.preventDefault(); if (off) return onSave([{ ...cell, id: entries.find((e) => e.status === "OFF")?.id || newRun().id, partNumber: "", buildQty: 0, status: "OFF" }]); for (const run of runs) { const validParent = parents.some((p) => p.stockCode === run.partNumber); if (run.activity === "Production" && (!validParent || Number(run.buildQty) <= 0)) return setError("Every production run requires a valid SYSPRO BOM parent and a quantity greater than zero."); if (run.activity === "Changeover" && run.partNumber && !validParent) return setError("The selected changeover destination is not a valid SYSPRO BOM parent."); } onSave(runs.map((run) => ({ ...cell, ...run, buildQty: Math.max(0, Number(run.buildQty) || 0), status: run.activity === "Changeover" ? "Changeover" : run.status || "Planned" }))); }
  return <div className="bm-editor-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><form className="bm-editor bm-shift-editor" onSubmit={submit}><div className="bm-editor-title">{cell.machine.replace("BM0", "BM")} · {cell.day} · {cell.shift}</div><label className="bm-off-toggle"><input type="checkbox" checked={off} onChange={(e) => setShiftOff(e.target.checked)} /> Shift OFF</label>{!off && runs.map((run, index) => <RunEditor key={run.id} run={run} index={index} parents={parents} productionLine={productionLine} onChange={(patch) => update(run.id, patch)} onRemove={() => setRuns((current) => current.filter((item) => item.id !== run.id))} removable={runs.length > 1} />)}{!off && <button type="button" className="bm-add-run" onClick={() => setRuns((current) => [...current, newRun()])}>+ Add Plan</button>}{productionLine === "thermoforming" && bomStatus?.loading && <div className="bm-editor-error">Loading SYSPRO BOM parents…</div>}{productionLine === "thermoforming" && !bomStatus?.connected && <div className="bm-editor-error">SYSPRO BOM unavailable.</div>}{missingAliases.length > 0 && <div className="bm-editor-error">{missingAliases.map((item) => `${item.shortName} (${item.stockCode})`).join(", ")} not available in current SYSPRO BOM.</div>}{error && <div className="bm-editor-error">{error}</div>}<div className="bm-editor-actions"><span /><button type="button" onClick={onClose}>Cancel</button><button type="submit" className="primary">Save Shift</button></div></form></div>;
}

function RunEditor({ run, index, parents, productionLine, onChange, onRemove, removable }) {
  const [query, setQuery] = useState(""); const selected = parents.find((p) => p.stockCode === run.partNumber); const q = query.trim().toLowerCase();
  const matches = useMemo(() => parents.filter((p) => !q || parentMatches(p, q) || p.family?.toLowerCase().includes(q) || p.market?.toLowerCase().includes(q)).slice(0, 60), [parents, q]);
  return <section className="bm-run-editor"><div className="bm-run-heading"><b>PLAN {index + 1}</b>{removable && <button type="button" onClick={onRemove}>Remove Plan {index + 1}</button>}</div><label>Activity<select value={run.activity} onChange={(e) => onChange({ activity: e.target.value })}><option>Production</option><option>Changeover</option></select></label><label>Product<input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search short name, stock code or description…" /></label>{selected ? <div className="bm-parent-selected"><strong>{selected.displayCode || selected.alias || selected.stockCode}</strong><span>{selected.stockCode} · {selected.description}</span><button type="button" onClick={() => onChange({ partNumber: "" })}>Change</button></div> : <div className="bm-parent-results">{matches.map((parent) => <button type="button" key={parent.id} onClick={() => { onChange({ partNumber: parent.stockCode }); setQuery(""); }}><strong>{parent.displayCode || parent.alias || parent.stockCode}</strong><span>{parent.stockCode}</span><span>{parent.description}</span></button>)}</div>}<label>Planned Qty<input type="number" min="0" step="any" value={run.buildQty} onChange={(e) => onChange({ buildQty: e.target.value })} /></label>{run.activity === "Production" && <label>Status<select value={run.status} onChange={(e) => onChange({ status: e.target.value })}><option>Planned</option><option>In progress</option><option>Completed</option><option>Blocked</option></select></label>}</section>;
}
