import React, { useMemo, useState } from "react";
import { ChevronRight, RotateCcw } from "lucide-react";
import { sysproBomParents } from "./sysproBom";

export default function SysproBomExplorer({ boms, status, onRefresh }) {
  const [search, setSearch] = useState(""); const [expanded, setExpanded] = useState(null);
  const parents = useMemo(() => { const q = search.trim().toLowerCase(); return sysproBomParents(boms).filter((p) => !q || p.parentStockCode.toLowerCase().includes(q) || p.parentDescription.toLowerCase().includes(q)); }, [boms, search]);
  return <section><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 }}><div><h1 style={{ margin: 0 }}>Bill of Materials</h1><p style={{ color: "#746C5C" }}>Source: Syspro {status.lastUpdated ? `· refreshed ${status.lastUpdated.toLocaleString()}` : ""}</p></div><button className="mrp-btn mrp-btn-primary" onClick={onRefresh} disabled={status.loading}><RotateCcw size={14} />{status.loading ? "Loading…" : "Refresh"}</button></div>{status.error && <div style={{ background: "#F3E1DE", color: "#A6362B", padding: 10, marginBottom: 12 }}>Syspro BOM unavailable: {status.error}{boms.length ? " · displaying stale in-memory data" : ""}</div>}<input className="mrp-input" style={{ width: "100%", maxWidth: 470, marginBottom: 12 }} value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search parent stock code or description…" />{!status.loading && !boms.length && <div>Syspro BOM unavailable</div>}<div style={{ background: "#fff", border: "1px solid #E3DFD2" }}>{parents.map((parent) => <div key={parent.parentStockCode} style={{ borderBottom: "1px solid #E3DFD2" }}><button onClick={() => setExpanded(expanded === parent.parentStockCode ? null : parent.parentStockCode)} style={{ width: "100%", border: 0, background: "#fff", padding: 12, display: "flex", gap: 10, textAlign: "left" }}><ChevronRight size={16} style={{ transform: expanded === parent.parentStockCode ? "rotate(90deg)" : "none" }} /><b>{parent.parentStockCode}</b><span>{parent.parentDescription}</span><span style={{ marginLeft: "auto" }}>{parent.components.length} components</span></button>{expanded === parent.parentStockCode && <table className="mrp-table"><thead><tr><th>Child Stock Code</th><th>Description</th><th style={{ textAlign: "right" }}>Qty Per</th></tr></thead><tbody>{parent.components.map((row, i) => <tr key={`${row.componentStockCode}-${i}`}><td className="plex-mono">{row.componentStockCode}</td><td>{row.componentDescription}</td><td className="plex-mono" style={{ textAlign: "right" }}>{row.qtyPer}</td></tr>)}</tbody></table>}</div>)}</div></section>;
}
