import React, { useState } from "react";
import { BOOTSTRAP_ADMIN, hashPassword, verifyPassword } from "./authService";
import { ROLES } from "./permissions";
import "./auth.css";

export function Login({ onLogin, bootstrap }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); if (!username.trim() || !password) return setError("Enter both username and password."); setBusy(true); setError(""); try { await onLogin(username, password); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  return <main className="auth-page"><form className="auth-card" onSubmit={submit}><h1>ATD Production MRP</h1><p>Sign in to continue</p><label>Username<input autoFocus autoComplete="username" value={username} onChange={(e) => setUsername(e.target.value)} /></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <div className="auth-error">{error}</div>}<button disabled={busy}>{busy ? "Signing in…" : "Login"}</button>{bootstrap && <div className="auth-bootstrap">First-time login: <b>{BOOTSTRAP_ADMIN.username}</b> / <b>{BOOTSTRAP_ADMIN.password}</b><br />You will be required to change this password.</div>}<small>Prototype: credentials are stored only in this browser.</small></form></main>;
}

export function ChangePassword({ user, required = false, onSave, onCancel }) {
  const [form, setForm] = useState({ current: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); if (!form.current || !form.password || !form.confirm) return setError("Complete all password fields."); if (form.password !== form.confirm) return setError("Password confirmation does not match."); if (form.password.length < 8) return setError("New password must be at least 8 characters."); setBusy(true); if (!(await verifyPassword(form.current, user.passwordHash))) { setBusy(false); return setError("Current password is incorrect."); } await onSave(await hashPassword(form.password)); setBusy(false); }
  return <div className="auth-modal"><form className="auth-card" onSubmit={submit}><h2>{required ? "Change your temporary password" : "Change Password"}</h2><label>Current password<input type="password" value={form.current} onChange={(e) => setForm({ ...form, current: e.target.value })} /></label><label>New password<input type="password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /></label><label>Confirm new password<input type="password" value={form.confirm} onChange={(e) => setForm({ ...form, confirm: e.target.value })} /></label>{error && <div className="auth-error">{error}</div>}<div className="auth-actions">{!required && <button type="button" className="secondary" onClick={onCancel}>Cancel</button>}<button disabled={busy}>Save Password</button></div></form></div>;
}

const emptyUser = { fullName: "", username: "", role: "SUPERVISOR", department: "", password: "", confirm: "" };
export function UsersPage({ users, currentUser, onSaveUsers }) {
  const [editing, setEditing] = useState(null); const [draft, setDraft] = useState(emptyUser); const [error, setError] = useState("");
  function open(user = null) { setEditing(user?.id || "new"); setDraft(user ? { ...user, password: "", confirm: "" } : emptyUser); setError(""); }
  async function save(e) { e.preventDefault(); const username = draft.username.trim(); if (!draft.fullName.trim() || !username || !draft.role) return setError("Full name, username and role are required."); if (editing === "new" && !draft.password) return setError("Password is required for a new user."); if (draft.password !== draft.confirm) return setError("Password confirmation does not match."); if (users.some((u) => u.id !== draft.id && u.username.toLocaleLowerCase() === username.toLocaleLowerCase())) return setError("That username is already in use."); const now = new Date().toISOString(); const existing = users.find((u) => u.id === draft.id); const user = { ...(existing || {}), id: existing?.id || `user_${crypto.randomUUID()}`, username, fullName: draft.fullName.trim(), role: draft.role, department: draft.department.trim(), isActive: existing?.isActive ?? true, mustChangePassword: existing?.mustChangePassword ?? true, createdAt: existing?.createdAt || now, updatedAt: now, lastLoginAt: existing?.lastLoginAt || null, passwordHash: draft.password ? await hashPassword(draft.password) : existing.passwordHash }; onSaveUsers(existing ? users.map((u) => u.id === user.id ? user : u) : [...users, user]); setEditing(null); }
  function toggle(user) { if (user.id === currentUser.id && user.isActive) return setError("You cannot deactivate your own account."); if (user.isActive && user.role === "ADMIN" && users.filter((u) => u.isActive && u.role === "ADMIN").length === 1) return setError("At least one active administrator is required."); onSaveUsers(users.map((u) => u.id === user.id ? { ...u, isActive: !u.isActive, updatedAt: new Date().toISOString() } : u)); }
  async function reset(user) { const password = prompt(`Temporary password for ${user.username} (minimum 8 characters):`); if (password === null) return; if (password.length < 8) return setError("Temporary password must be at least 8 characters."); const passwordHash = await hashPassword(password); onSaveUsers(users.map((u) => u.id === user.id ? { ...u, passwordHash, mustChangePassword: true, updatedAt: new Date().toISOString() } : u)); setError("Password reset. The user must change it at next login."); }
  return <section className="users-page"><div className="users-header"><div><h1>Users</h1><p>Local prototype accounts and access roles</p></div><button onClick={() => open()}>Add User</button></div>{error && <div className="auth-notice">{error}</div>}<div className="users-table-wrap"><table className="mrp-table"><thead><tr><th>Full Name</th><th>Username</th><th>Role</th><th>Department</th><th>Status</th><th>Last Login</th><th>Actions</th></tr></thead><tbody>{users.map((u) => <tr key={u.id}><td>{u.fullName}</td><td>{u.username}</td><td>{u.role}</td><td>{u.department || "—"}</td><td><span className={u.isActive ? "status active" : "status"}>{u.isActive ? "Active" : "Inactive"}</span></td><td>{u.lastLoginAt ? new Date(u.lastLoginAt).toLocaleString() : "Never"}</td><td className="user-actions"><button onClick={() => open(u)}>Edit</button><button onClick={() => reset(u)}>Reset password</button><button onClick={() => toggle(u)}>{u.isActive ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table></div>{editing && <div className="auth-modal"><form className="auth-card user-form" onSubmit={save}><h2>{editing === "new" ? "Add User" : "Edit User"}</h2><label>Full Name<input value={draft.fullName} onChange={(e) => setDraft({ ...draft, fullName: e.target.value })} /></label><label>Username<input value={draft.username} onChange={(e) => setDraft({ ...draft, username: e.target.value })} /></label><label>Role<select value={draft.role} onChange={(e) => setDraft({ ...draft, role: e.target.value })}>{ROLES.map((r) => <option key={r}>{r}</option>)}</select></label><label>Department<input value={draft.department} onChange={(e) => setDraft({ ...draft, department: e.target.value })} /></label><label>{editing === "new" ? "Password" : "New password (optional)"}<input type="password" value={draft.password} onChange={(e) => setDraft({ ...draft, password: e.target.value })} /></label><label>Confirm password<input type="password" value={draft.confirm} onChange={(e) => setDraft({ ...draft, confirm: e.target.value })} /></label>{error && <div className="auth-error">{error}</div>}<div className="auth-actions"><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button><button>Save User</button></div></form></div>}</section>;
}
