import React, { useMemo, useState } from "react";
import { CheckCircle2, ClipboardCheck, Plus, Search, Trash2 } from "lucide-react";
import { CYCLE_COUNT_REASONS, reasonLabel } from "./cycleCountReasons";
import { CYCLE_COUNT_SHIFTS, addDailyItem, automaticStatus, calculateVariance, createCycleCountDay, formatQuantity, hasPhysicalCount, inventoryCode, inventoryDescription, inventoryUom } from "./cycleCountUtils";
import { PRODUCTION_LINES } from "../production/productionLines";
import "./cycleCount.css";

const todayISO = () => new Date().toISOString().slice(0, 10);
const userName = (users, id) => users.find((user) => user.id === id)?.fullName || "Unassigned";
const matches = (item, term) => [inventoryCode(item), inventoryDescription(item), inventoryUom(item)].some((value) => value.toLocaleLowerCase().includes(term));

function MaterialSearch({ inventory, status, selectedItems, disabled, onAdd, compact = false }) {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(null);
  const selectedCodes = useMemo(() => new Set(selectedItems.map((item) => item.stockCode.toUpperCase())), [selectedItems]);
  const results = useMemo(() => {
    const term = query.trim().toLocaleLowerCase();
    if (!term || status !== "connected") return [];
    return inventory.filter((item) => !selectedCodes.has(inventoryCode(item).toUpperCase()) && matches(item, term)).slice(0, 30);
  }, [inventory, query, selectedCodes, status]);
  function add() { if (!selected || disabled) return; onAdd(selected); setSelected(null); setQuery(""); }
  return <div className={`cc-material-search${compact ? " compact" : ""}`}>
    <b>ADD MATERIAL</b>
    <div className="cc-search"><Search size={15} /><input value={query} disabled={status !== "connected" || disabled} onChange={(event) => { setQuery(event.target.value); setSelected(null); }} placeholder="Search stock code or description..." /></div>
    {status === "loading" && <p className="cc-search-state">Loading stock codes...</p>}
    {status === "offline" && <p className="cc-search-state error">Stock-code search unavailable — Syspro inventory is offline.</p>}
    {status === "connected" && query.trim() && !selected && <div className="cc-results">{results.map((item) => <button type="button" key={inventoryCode(item)} onClick={() => { setSelected(item); setQuery(inventoryCode(item)); }}><b>{inventoryCode(item)}</b><span>{inventoryDescription(item)}</span><small>UOM: {inventoryUom(item)}</small></button>)}{!results.length && <p>No matching unselected stock codes.</p>}</div>}
    {selected && <div className="cc-selected-material"><div><b>{inventoryCode(selected)}</b><span>{inventoryDescription(selected)}</span><small>UOM: {inventoryUom(selected)}</small></div><button type="button" className="mrp-btn mrp-btn-primary" disabled={disabled} onClick={add}><Plus size={14} /> Add to Cycle Count</button></div>}
    {disabled && status === "connected" && <p className="cc-search-state">Materials cannot be added after a shift has been submitted.</p>}
  </div>;
}

export default function CycleCount({ days, setDays, inventory, inventoryStatus, productionLine, users, currentUser, canSetup, canCount, canReopen }) {
  const [date, setDate] = useState(todayISO()), [mode, setMode] = useState("entry"), [shift, setShift] = useState("morning"), [setupOpen, setSetupOpen] = useState(false);
  const day = days.find((entry) => entry.date === date && entry.productionLine === productionLine);
  const assignment = day?.shifts.find((entry) => entry.shift === shift);
  const isAssigned = assignment?.supervisorUserId === currentUser.id || assignment?.teamLeaderUserId === currentUser.id;
  const mayEditCount = canReopen || (canCount && isAssigned), locked = Boolean(assignment?.submittedAt);
  const records = day?.countRecords.filter((record) => record.shift === shift) || [];
  const counted = records.filter((record) => hasPhysicalCount(record.physicalCount)).length;
  const activeUsers = users.filter((user) => user.isActive), listLocked = day?.shifts.some((entry) => entry.submittedAt);

  function updateDay(mutator) { setDays((current) => { const existing = current.find((entry) => entry.date === date && entry.productionLine === productionLine); if (!existing) return current; const next = mutator(existing); return current.map((entry) => entry.id === existing.id ? next : entry); }); }
  function ensureDay() { if (canSetup && !day) setDays((current) => [...current, createCycleCountDay(date, productionLine, currentUser.id)]); }
  function addItem(item) { if (canSetup && !listLocked) updateDay((current) => addDailyItem(current, item, currentUser.id)); }
  function removeItem(stockCode) { if (canSetup && !listLocked) updateDay((current) => ({ ...current, items: current.items.filter((item) => item.stockCode !== stockCode), countRecords: current.countRecords.filter((record) => record.stockCode !== stockCode), updatedByUserId: currentUser.id, updatedAt: new Date().toISOString() })); }
  function updateAssignment(field, value) { if (canSetup && !locked) updateDay((current) => ({ ...current, shifts: current.shifts.map((entry) => entry.shift === shift ? { ...entry, [field]: value } : entry), updatedByUserId: currentUser.id, updatedAt: new Date().toISOString() })); }
  function updateRecord(stockCode, field, value) { if (!mayEditCount || locked) return; updateDay((current) => ({ ...current, countRecords: current.countRecords.map((record) => { if (record.shift !== shift || record.stockCode !== stockCode) return record; const now = new Date().toISOString(), next = { ...record, [field]: value, updatedByUserId: currentUser.id, updatedAt: now }; if (field === "physicalCount") { next.variance = calculateVariance(value, record.expectedEosSoh); next.status = automaticStatus(value, record.expectedEosSoh); next.countedByUserId = hasPhysicalCount(value) ? currentUser.id : null; next.countedAt = hasPhysicalCount(value) ? (record.countedAt || now) : null; } return next; }), updatedByUserId: currentUser.id, updatedAt: new Date().toISOString() })); }
  function submitShift() { if (!mayEditCount || locked || counted !== records.length || !records.length) return; if (records.some((record) => record.reasonCode === "OTHER" && !record.reasonComment.trim())) return window.alert("A comment is required when the reason is Other."); updateDay((current) => ({ ...current, shifts: current.shifts.map((entry) => entry.shift === shift ? { ...entry, submittedByUserId: currentUser.id, submittedAt: new Date().toISOString() } : entry), updatedByUserId: currentUser.id, updatedAt: new Date().toISOString() })); }

  const header = <><header className="cc-header"><div><span>Cycle Count</span><h1>{PRODUCTION_LINES[productionLine]?.name} — Cycle Count</h1><p>{new Date(`${date}T12:00:00`).toLocaleDateString(undefined, { day: "2-digit", month: "short", year: "numeric" })}</p></div><label>Date<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label></header><div className="cc-mode"><button className={mode === "entry" ? "active" : ""} onClick={() => setMode("entry")}>Count Entry</button><button className={mode === "summary" ? "active" : ""} onClick={() => setMode("summary")}>Daily Summary</button>{canSetup && day && <button onClick={() => setSetupOpen(!setupOpen)}>Daily Setup</button>}</div></>;
  if (!day) return <div className="cycle-count">{header}<div className="cc-empty"><ClipboardCheck size={34} /><h2>No cycle count plan</h2><p>Create the shared daily material list for this date and production line.</p>{canSetup && <button className="mrp-btn mrp-btn-primary" onClick={ensureDay}><Plus size={15} /> Create Daily Count</button>}</div></div>;
  return <div className="cycle-count">{header}
    {setupOpen && canSetup && <section className="cc-setup"><h2>Daily Setup</h2><MaterialSearch inventory={inventory} status={inventoryStatus} selectedItems={day.items} disabled={listLocked} onAdd={addItem} compact /><table className="mrp-table"><thead><tr><th>Stock Code</th><th>Description</th><th>UOM</th><th></th></tr></thead><tbody>{day.items.map((item) => <tr key={item.stockCode}><td className="plex-mono">{item.stockCode}</td><td>{item.description}</td><td>{item.uom}</td><td><button className="cc-icon" disabled={listLocked} onClick={() => removeItem(item.stockCode)}><Trash2 size={14} /></button></td></tr>)}</tbody></table></section>}
    {mode === "entry" ? <><div className="cc-shifts">{CYCLE_COUNT_SHIFTS.map((item) => <button key={item.id} className={shift === item.id ? "active" : ""} onClick={() => setShift(item.id)}>{item.label}</button>)}</div><section className="cc-assignment"><label>Supervisor<select value={assignment?.supervisorUserId || ""} disabled={!canSetup || locked} onChange={(event) => updateAssignment("supervisorUserId", event.target.value)}><option value="">Unassigned</option>{activeUsers.map((user) => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></label><label>Team Leader<select value={assignment?.teamLeaderUserId || ""} disabled={!canSetup || locked} onChange={(event) => updateAssignment("teamLeaderUserId", event.target.value)}><option value="">Unassigned</option>{activeUsers.map((user) => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></label><div className="cc-progress"><b>{counted} / {records.length} Counted</b><span>{records.length - counted} Outstanding</span></div>{locked && <div className="cc-submitted"><CheckCircle2 size={16} /> Submitted by {userName(users, assignment.submittedByUserId)} · {new Date(assignment.submittedAt).toLocaleString()}</div>}</section>{canSetup && <MaterialSearch inventory={inventory} status={inventoryStatus} selectedItems={day.items} disabled={listLocked} onAdd={addItem} />}{!day.items.length ? <div className="cc-no-materials"><b>No stock codes selected for this Cycle Count.</b><span>Search above to add a stock code,<br />or use Daily Setup to build the full count list.</span></div> : <CountTable day={day} records={records} mayEditCount={mayEditCount} locked={locked} updateRecord={updateRecord} />}<div className="cc-submit"><button className="mrp-btn mrp-btn-primary" disabled={!mayEditCount || locked || counted !== records.length || !records.length} onClick={submitShift}>Submit Shift Count</button></div></> : <DailySummary day={day} users={users} />}
  </div>;
}

function CountTable({ day, records, mayEditCount, locked, updateRecord }) {
  return <div className="cc-table-wrap"><table className="mrp-table cc-entry"><thead><tr><th>Stock Code</th><th>Description</th><th>UOM</th><th>EOS SOH</th><th>Physical Count</th><th>Variance</th><th>Reason</th><th>Comment</th><th>Status</th></tr></thead><tbody>{day.items.map((item) => { const record = records.find((entry) => entry.stockCode === item.stockCode); return <tr key={item.stockCode}><td className="plex-mono">{item.stockCode}</td><td>{item.description}</td><td>{item.uom}</td><td className="plex-mono">{formatQuantity(record?.expectedEosSoh)}</td><td><input type="number" step="any" value={record?.physicalCount ?? ""} disabled={!mayEditCount || locked} onChange={(event) => updateRecord(item.stockCode, "physicalCount", event.target.value === "" ? null : Number(event.target.value))} /></td><td className={`plex-mono variance ${record?.variance < 0 ? "negative" : record?.variance > 0 ? "positive" : ""}`}>{record?.variance > 0 ? "+" : ""}{formatQuantity(record?.variance)}</td><td><select value={record?.reasonCode || ""} disabled={!mayEditCount || locked} onChange={(event) => updateRecord(item.stockCode, "reasonCode", event.target.value)}><option value="">Select reason</option>{CYCLE_COUNT_REASONS.map((reason) => <option key={reason.value} value={reason.value}>{reason.label}</option>)}</select></td><td><input value={record?.reasonComment || ""} disabled={!mayEditCount || locked} onChange={(event) => updateRecord(item.stockCode, "reasonComment", event.target.value)} placeholder={record?.reasonCode === "OTHER" ? "Required" : "Optional"} /></td><td><span className={`cc-status ${record?.status?.toLowerCase()}`}>{record?.status?.replaceAll("_", " ")}</span></td></tr>; })}</tbody></table></div>;
}

function DailySummary({ day, users }) {
  return <><div className="cc-summary-assignments">{CYCLE_COUNT_SHIFTS.map((shift) => { const assignment = day.shifts.find((entry) => entry.shift === shift.id); return <div key={shift.id}><b>{shift.label}</b><span>Supervisor: {userName(users, assignment?.supervisorUserId)}</span><span>Team Leader: {userName(users, assignment?.teamLeaderUserId)}</span></div>; })}</div><div className="cc-table-wrap"><table className="mrp-table cc-summary"><thead><tr><th rowSpan="2">Stock Code</th><th rowSpan="2">Description</th><th rowSpan="2">UOM</th>{CYCLE_COUNT_SHIFTS.map((shift) => <th key={shift.id} colSpan="4">{shift.label}</th>)}</tr><tr>{CYCLE_COUNT_SHIFTS.flatMap((shift) => ["EOS SOH", "Physical", "Variance", "Reason"].map((label) => <th key={`${shift.id}-${label}`}>{label}</th>))}</tr></thead><tbody>{day.items.map((item) => <tr key={item.stockCode}><td className="plex-mono">{item.stockCode}</td><td>{item.description}</td><td>{item.uom}</td>{CYCLE_COUNT_SHIFTS.flatMap((shift) => { const record = day.countRecords.find((entry) => entry.shift === shift.id && entry.stockCode === item.stockCode); return [<td key={`${shift.id}-e`} className="plex-mono">{formatQuantity(record?.expectedEosSoh)}</td>, <td key={`${shift.id}-p`} className="plex-mono">{formatQuantity(record?.physicalCount)}</td>, <td key={`${shift.id}-v`} className={`plex-mono ${record?.variance < 0 ? "negative" : record?.variance > 0 ? "positive" : ""}`}>{record?.variance > 0 ? "+" : ""}{formatQuantity(record?.variance)}</td>, <td key={`${shift.id}-r`}>{reasonLabel(record?.reasonCode)}</td>]; })}</tr>)}</tbody></table></div></>;
}
