import React, { useMemo } from "react";
import { AlertTriangle, Boxes, ClipboardList, Factory, Gauge, PackageCheck, Radio } from "lucide-react";
import { deriveDashboardSummary } from "./deriveDashboardSummary";
import { PRODUCTION_LINES } from "../production/productionLines";

const colors = { ink: "#1B2430", card: "#FFFFFF", line: "#E3DFD2", muted: "#746C5C", copper: "#0868B2", brick: "#A6362B", brickTint: "#F3E1DE", green: "#2F6F4E", greenTint: "#E1EBE3" };
const fmt = (value) => value === null || value === undefined ? "—" : (Math.round((Number(value || 0) + Number.EPSILON) * 100) / 100).toLocaleString(undefined, { maximumFractionDigits: 2 });
const pct = (value) => value === null || value === undefined ? "—" : `${fmt(value)}%`;
const machineLabel = (machine) => machine.replace("BM0", "BM");

function KpiCard({ label, value, caption, icon: Icon, format = fmt, alert = false }) {
  const activeAlert = Boolean(alert);
  return <div style={{ background: colors.card, border: `1px solid ${colors.line}`, borderTop: `3px solid ${activeAlert ? colors.brick : colors.copper}`, borderRadius: 5, padding: "12px 13px" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 8 }}><span style={{ color: colors.muted, fontSize: 10, fontWeight: 700, letterSpacing: ".05em", textTransform: "uppercase" }}>{label}</span><Icon size={15} color={activeAlert ? colors.brick : colors.copper} /></div><div className="plex-mono" style={{ color: activeAlert ? colors.brick : colors.ink, fontSize: 25, fontWeight: 600, marginTop: 5 }}>{format(value)}</div><div style={{ color: colors.muted, fontSize: 10, marginTop: 2 }}>{caption}</div></div>;
}

function StatusBadge({ status }) {
  const danger = ["Consumption variance", "Stock balance variance", "Insufficient RAW stock", "Pack size missing", "Data incomplete"].includes(status);
  const ready = status === "Ready to request";
  return <span style={{ padding: "3px 6px", borderRadius: 3, whiteSpace: "nowrap", fontSize: 10, fontWeight: 700, background: danger ? colors.brickTint : ready ? colors.greenTint : colors.line, color: danger ? colors.brick : ready ? colors.green : colors.muted }}>{status}</span>;
}

export default function PlannerDashboard({ planning, productionActuals, productionMrp, materialReconciliation, reconciliationAvailable, sysproStatus, sysproLastUpdated, productionLine = "blowMoulding" }) {
  const line = PRODUCTION_LINES[productionLine];
  const dashboard = useMemo(() => deriveDashboardSummary({ planning, productionActuals, productionMrp, materialReconciliation, reconciliationAvailable, productionLine }), [planning, productionActuals, productionMrp, materialReconciliation, reconciliationAvailable, productionLine]);
  return <div style={{ display: "flex", flexDirection: "column", gap: 15 }}>
    <section style={{ background: colors.ink, color: "#fff", borderRadius: 7, padding: "16px 19px", display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 15, flexWrap: "wrap" }}><div><div style={{ fontSize: 23, fontWeight: 600 }}>{line.name} Production Control</div><div style={{ color: "#D9D4C4", fontSize: 12, marginTop: 4 }}>Active week: <span className="plex-mono">{planning?.weekStart || "—"}</span></div></div><div style={{ fontSize: 11, color: sysproStatus === "connected" ? "#9DD6B8" : "#E7A8A2", textAlign: "right" }}><div style={{ display: "flex", alignItems: "center", gap: 5 }}><Radio size={13} /> Syspro: {sysproStatus === "connected" ? "Connected" : sysproStatus === "loading" ? "Connecting…" : "Offline"}</div><div style={{ color: "#8C93A0", marginTop: 4 }}>{sysproLastUpdated ? `Last refreshed: ${sysproLastUpdated.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}` : "Using local/last-known inventory values"}</div></div></section>

    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10 }}><KpiCard label="Original Planned" value={dashboard.originalPlannedSets} caption={`active-week ${line.quantityLabel.toLowerCase()}`} icon={Factory} /><KpiCard label="Effective Planned" value={dashboard.plannedSets} caption={`adjustment ${fmt(dashboard.planAdjustment)}`} icon={Factory} /><KpiCard label={`Actual ${line.quantityLabel}`} value={dashboard.actualSets} caption="supervisor-captured output" icon={Gauge} /><KpiCard label="Production Variance" value={dashboard.productionVariance} caption="actual minus effective plan" icon={ClipboardList} alert={dashboard.productionVariance < 0} /><KpiCard label="Achievement" value={dashboard.achievementPct} format={pct} caption="actual / effective plan" icon={Gauge} /></section>
    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", gap: 10 }}><KpiCard label="Child Materials" value={dashboard.childMaterials} caption="unique Production MRP children" icon={Boxes} /><KpiCard label="Materials to Request" value={dashboard.materialsToRequest} caption="positive store request quantity" icon={PackageCheck} /><KpiCard label="RAW Shortages" value={dashboard.rawShortages} caption="unique shortage materials" icon={AlertTriangle} alert={dashboard.rawShortages > 0} /><KpiCard label="Material Variances" value={dashboard.materialVariances} caption="consumption or stock variance" icon={AlertTriangle} alert={dashboard.materialVariances > 0} />{productionLine === "thermoforming" && <KpiCard label="Expected Tailgates" value={dashboard.productSummary.tailgateExpectedFromPlan} caption={`actual output: ${fmt(dashboard.productSummary.tailgateExpectedFromActual)}`} icon={Factory} />}</section>
    <div style={{ display: "flex", gap: 15, flexWrap: "wrap", color: colors.muted, fontSize: 11 }}>Reconciliation: <span>Tied <b style={{ color: colors.ink }}>{dashboard.reconciliationIndicators.tied}</b></span><span>Pending BKF <b style={{ color: colors.ink }}>{dashboard.reconciliationIndicators.pendingBkf}</b></span><span>Data Issues <b style={{ color: colors.ink }}>{dashboard.reconciliationIndicators.dataIssues}</b></span></div>
    {!reconciliationAvailable && <div style={{ background: "#FFF1C7", color: "#765400", padding: "8px 11px", borderRadius: 4, fontSize: 11 }}>Material reconciliation unavailable — Syspro transaction data and period WIP balances are not loaded.</div>}

    <section style={{ background: colors.card, border: `1px solid ${colors.line}`, borderRadius: 6, overflow: "hidden" }}><div style={{ padding: "11px 14px", borderBottom: `1px solid ${colors.line}` }}><b>Machine Production Performance</b><div style={{ color: colors.muted, fontSize: 11, marginTop: 2 }}>Mould-set output for the active planning week.</div></div><table className="mrp-table"><thead><tr><th>Machine</th><th style={{ textAlign: "right" }}>Original Plan</th><th style={{ textAlign: "right" }}>Effective Plan</th><th style={{ textAlign: "right" }}>Plan Adjustment</th><th style={{ textAlign: "right" }}>Actual</th><th style={{ textAlign: "right" }}>Production Variance</th><th style={{ textAlign: "right" }}>Achievement</th></tr></thead><tbody>{dashboard.machinePerformance.map((row) => <tr key={row.machine}><td style={{ fontWeight: 700 }}>{machineLabel(row.machine)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.originalPlanned)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.planned)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.planAdjustment)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.actual)}</td><td className="plex-mono" style={{ textAlign: "right", color: row.variance < 0 ? colors.brick : row.variance > 0 ? colors.green : colors.ink }}>{fmt(row.variance)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{pct(row.achievementPct)}</td></tr>)}</tbody></table></section>

    <section style={{ background: colors.card, border: `1px solid ${colors.line}`, borderRadius: 6, overflow: "hidden" }}><div style={{ padding: "11px 14px", borderBottom: `1px solid ${colors.line}` }}><b>Material Attention</b><div style={{ color: colors.muted, fontSize: 11, marginTop: 2 }}>Combined existing Production MRP and available reconciliation outcomes.</div></div><div style={{ overflowX: "auto" }}><table className="mrp-table" style={{ minWidth: 940 }}><thead><tr><th>Stock Code</th><th>Description</th><th style={{ textAlign: "right" }}>Expected Consumption</th><th style={{ textAlign: "right" }}>System Consumption</th><th style={{ textAlign: "right" }}>Consumption Variance</th><th style={{ textAlign: "right" }}>Production Shortfall</th><th style={{ textAlign: "right" }}>RAW Shortage</th><th>Status</th></tr></thead><tbody>{dashboard.materialAttention.map((row) => <tr key={row.stockCode}><td className="plex-mono" style={{ fontWeight: 600 }}>{row.stockCode}</td><td>{row.description}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.expectedConsumptionQty)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.systemConsumptionQty)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.consumptionVarianceQty)}</td><td className="plex-mono" style={{ textAlign: "right" }}>{fmt(row.productionShortfall)}</td><td className="plex-mono" style={{ textAlign: "right", color: row.rawShortageQty > 0 ? colors.brick : colors.muted }}>{fmt(row.rawShortageQty)}</td><td><StatusBadge status={row.status} /></td></tr>)}{!dashboard.materialAttention.length && <tr><td colSpan={8} style={{ padding: 16, color: colors.muted }}>No materials currently require attention.</td></tr>}</tbody></table></div></section>
  </div>;
}
